config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'home/index'

  resources :groups
  post 'groups/import', to: 'groups#import'
  get  'create_group', to: 'groups#create_group'
  get  'download_csv',  to: 'groups#download'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  # association
  belongs_to :user
  belongs_to :group

  # validation
  validates :user_id, :group_id, :role, presence: true
  validates_uniqueness_of :role, scope: %i[user_id group_id], message: "User already exist in this event."

  enum role: [:organizer, :presenter, :participant]

  def role_name
    role.titleize
  end
end

app/models/group.rb
class Group < ApplicationRecord
  # association
  has_many :events, dependent: :destroy
  has_many :users, through: :events

  # validation
  validates :name, presence: true
  validates :name, uniqueness: true

  def group_name
    name.titleize
  end

  def organizer_name
    event = events.organizer.first
    event.user.name if event
  end

  def self.get_group(data)
    Group.find_or_create_by!(name: data['Group Name']&.downcase)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # association
  has_many :events
  has_many :groups, through: :events

  # validation
  validates :first_name, :last_name, presence: true
  validates :first_name, uniqueness: { scope: :last_name,
    message: "User already exist." }

  def name
    (first_name + ' ' + last_name).titleize
  end

  def self.get_user(data)
    User.find_or_create_by!(first_name: data['First Name']&.downcase, last_name: data['Last Name']&.downcase)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  require 'csv'

  before_action :set_group, only: [:show, :destroy, :edit, :update]

  def index
    @groups = Group.all.order('created_at DESC')
  end

  def show
    @users = @group.users
    @events = @group.events.order('role')
  end

  def create_group
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to @group
    else
      render 'edit'
    end
  end

  def destroy
    if @group.destroy
      flash[:notice] = "Successfully deleted group!"
    else
      flash[:alert] = "Error deleting group!"
    end
    respond_to do |format|
      format.html { redirect_to groups_path }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

  def import
    begin
      CSV.foreach(params[:file].path, headers: true) do |row|
        data = row.to_hash
        user = User.get_user(data)
        group = Group.get_group(data)
        event = Event.new(user_id: user.id, group_id: group.id, role: data['Role in Group']&.downcase)
        event.save!
      end
      flash[:notice] = "Successfully import group!"
      redirect_to groups_path
    rescue => e
      flash[:error] = "Error " + e.message
      redirect_to create_group_path
    end
  end

  def download
    send_file sample_file_path, type: "application/csv", disposition: 'attachment'
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name)
  end

  def sample_file_path
    "#{Rails.root}/public/sample_csv.csv"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def home_controller?
    params[:controller].eql?('home')
  end

  def groups_index_action?
    (params[:controller] == 'groups') && (params[:action] == 'index')
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/groups/_download_sample_csv.html.erb
<div class="page-header"><h1>Download Sample CSV</h1></div>
<div class="sub-container">
  <div class='row'>
    <div class='col-sm-6'>
      <p>Before Import CSV, please download this sample CSV.</p>
      <p>Here you can check CSV file format.<br/>Please do not change header of CSV.<br/>Start input from second line.</p>
      <p>Thanks!</p>
      <%= link_to 'Download Sample CSV', download_csv_path, class: 'btn btn-warning' %>
    </div>
    <div class='col-sm-6'>
      <p>Instruction :</p>
      <ol class="list-group">
        <li class="list-group-item">
          <p>Please choose user's role between <b>Organizer, Presenter</b> and <b>Participant</b></p>
        </li>
        <li class="list-group-item">
          <p>Make Sure <b>Organizer</b> of group present in CSV.</p>
        </li>
      </ol>
    </div>
  </div>
</div>

app/views/groups/_import_group.html.erb
<div class="page-header"><h1>Import Group</h1></div>
<div class="sub-container">
  <div class="form-group">
    <label for="importCSV">Import data from CSV</label>
    <%= form_tag groups_import_path, multipart: true do %>
      <%= file_field_tag :file, required: true, class: "form-control-file" %>
      <div class='row mt-20'>
        <div class='col-md-6'>
          <%= submit_tag 'Import CSV', class: 'btn btn-info btn-width' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/create_group.html.erb
<%= render partial: 'import_group' %>
<%= render partial: 'download_sample_csv' %>

app/views/groups/destroy.js.erb
$('.delete_group').bind('ajax:success', function() {
  $(this).closest('tr').fadeOut();
});

app/views/groups/edit.html.erb
<div class="page-header"><h1>Edit <%= @group.group_name %></h1></div>
<div class="sub-container">
  <%= form_with(model: @group, local: true) do |form| %>
    <div class="form-group">
      <label for="exampleInputEmail1">Name</label>
      <%= form.text_field :name, class: "form-control width-50", placeholder: "name" %>
    </div>
    <div class='row'>
      <div class='col-md-10'>
        <%= form.submit class: 'btn btn-primary' %>
      </div>
      <div class='col-md-2'>
        <%= link_to 'Back', group_path(@group), class: 'btn btn-info' %>
      </div>
    </div>
  <% end %>
</div>

app/views/groups/index.html.erb
<div class="page-header"><h1>Groups</h1></div>
<% if @groups.blank? %>
  <div class='text-center'>
    <h5> No group created yet!!!!</h5>
  </div>
<% else %>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Organizer</th>
        <th scope="col">Group Name</th>
        <th scope="col">Users</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody style="background-color: #eeeeee;">
      <% @groups.each do |group | %>
        <tr>
          <td><%= group.organizer_name %></td>
          <td><%= group.group_name %></td>
          <td><%= group.users.count %></td>
          <td>
            <%= link_to 'View', group_path(group), class: 'btn btn-success' %>
            <%= link_to 'Edit', edit_group_path(group), class: 'btn btn-primary' %>
            <%= link_to 'Remove', group_path(group), remote: true, class: 'btn btn-danger delete_group', method: :delete, data: {confirm: 'Are you sure?'} %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<%= link_to 'Create Group', create_group_path, class: 'btn btn-info' %>

app/views/groups/show.html.erb
<div class="page-header"><h1><%= @group.group_name %></h1></div>
<div class="page-header"><h3>Users</h3></div>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Role</th>
    </tr>
  </thead>
  <tbody style="background-color: #eeeeee;">
    <% @events.each do |event| %>
      <tr>
        <td><%= event.user.name %></td>
        <td><%= event.role_name %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class='row'>
  <div class='col-md-10'>
    <%= link_to 'Edit', edit_group_path(@group), class: 'btn btn-primary' %>
  </div>
  <div class='col-md-2'>
    <%= link_to 'Back', groups_path, class: 'btn btn-info' %>
  </div>
</div>

app/views/home/index.html.erb
<div class='page-header'><h1>Lets MeetUp</h1></div>
<div class="main-container">
  <div class="row">
    <div class="center-block">
      <h1>Hello,</h1>
      <p>Welcome to RealmFive Meetup.</p>
      <p>Here you can create a group and manage users for MeetUp.</p>
      <div class="col-md-8 text-center">
        <%= link_to 'Start', groups_path, class: 'btn btn-info btn-width' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert" id='flash'>
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default head-bg" role="navigation">
  <div class="navbar-header">
    <a class="navbar-brand" href="#">RealmFive MeetUp</a>
  </div>
  <div class="collapse navbar-collapse" id="navbar-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to 'Home', root_path unless home_controller? %></li>
      <li><%= link_to 'Groups', groups_path unless groups_index_action? %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RealmfiveMeetup</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation'%>
    <%= render 'layouts/messages' %>
    <div class="container-fluid">
      <div class="container">
        <%= yield %>
      </div>
    </div>
  </body>
</html>